version: "3.9"

services:
  postgres_service:
    container_name: postgres_container
    image: postgres:latest
    volumes:
      - twitter_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=twitter_db
    expose:
      - 5432
# Uncomment it if you need db port to be exposed
#    ports:
#      - "5432:5432"


  django_service:
    container_name: django_container
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_service

volumes:
  twitter_postgres_data: